### ISSUE TITLE
Por Favor Add Config & Other Stuff

### ISSUE THREAD

**Issue by Mostovm** [SharaGGa/RetroHungerMod#2]
Thank you for not removing sprinting mechanic. 
& rotten flesh gives 4 hp for what its worth.

Also pls add config for;
Foods health multiplier
Consume instantly

thank you

**Comment by Shi3ofreniR** [comment]
This mod involves the simplest mechanics for implementing instant food consumption and health point restoration, as it was in the old alpha versions of Minecraft, without adding additional functions and their settings. Moreover, since I'm only a beginner developer, I probably won't be able to implement settings for health multipliers and instant food consumption.

I apologize if I've disappointed you.🙏
I hope for your understanding.

**Comment by Mostovm** [comment]
okay fair enough ty
